yarnPath: .yarn/releases/yarn-3.3.0.cjs
nodeLinker: pnp

packageExtensions:
  "@mantine/styles@*":
    dependencies:
      "@emotion/cache": "*"
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
